.PHONY: all clean

all:
	$(MAKE) -C 11 all
	$(MAKE) -C 12 all
	$(MAKE) -C 13 all
	$(MAKE) -C 15 all
	$(MAKE) -C 24 all

clean:
	$(MAKE) -C 11 clean
	$(MAKE) -C 12 clean
	$(MAKE) -C 13 clean
	$(MAKE) -C 15 clean
	$(MAKE) -C 24 clean
